// Code generated by Slice Machine. DO NOT EDIT.

import { defineSliceZoneComponents } from "@prismicio/vue";
import HomeHero from "./HomeHero/index.vue";
import FeaturedProjects from "./FeaturedProjects/index.vue";
import HomeAboutSection from "./HomeAboutSection/index.vue";
import HomeProductsSlider from "./HomeProductsSlider/index.vue";
import ProductCard from "./ProductCard/index.vue";
import ProjectCard from "./ProjectCard/index.vue";
import Testimonials from "./Testimonials/index.vue";

export const components = defineSliceZoneComponents({
  featured_projects: FeaturedProjects,
  home_about_section: HomeAboutSection,
  home_hero: HomeHero,
  home_products_slider: HomeProductsSlider,
  product_card: ProductCard,
  projects: ProjectCard,
  testimonials: Testimonials,
});
